機能仕様書に「健康状態一覧表示機能」の機能仕様を記述しました。
ShirahamaTakuma/healthcare_application pull request #1
Opened 2021-12-15 01:50 UTC by ShirahamaTakuma

健康状態管理アプリの1つ目の機能である「健康状態一覧表示機能」について、機能仕様を機能仕様書に記述しました。
機能仕様書のレビューをよろしくお願いいたします。
また、プルリクエストの文面自体に対する指摘点もございましたら、いただけると幸いです。

※ 第1イテレーションでは他に「健康状態・ひとこと登録機能」のレビューも行っていただきますが、そちらは機能仕様追記が完了し次第、別のプルリクエストでレビュー依頼を提示させていただきます。

機能仕様書プレビュー

2021-12-15 02:44 UTC, iwanam requested changes
ちょっと拡大解釈したとこや素朴な疑問なども含めていくつか指摘してみました（全部対応してってことではないです）
- 異常系は特にないですか？
- 画面イメージからすると、文字列の長さとか制限はありますか？
- 例えば、状況によって何か色が変わったりとかあります？
- 何も登録がない場合どんな表示になります？
- 一覧ということですが、個人ごとの一覧になります？それとも日ごとにメンバー全員の一覧になります？

2021-12-15 03:07 UTC, ShirahamaTakuma commented
> ちょっと拡大解釈したとこや素朴な疑問なども含めていくつか指摘してみました（全部対応してってことではないです）

ご指摘いただきありがとうございます。
以下回答になります。

> * 異常系は特にないですか？

「健康状態一覧表示機能」における異常系は特に考えられませんでした（ユーザーはタイムライン画面にアクセスするだけなので）。
データベースに接続出来ない場合などの異常系も考えましたが、コーチャーに確認を取ったところ機能仕様書には書かなくても良いとの回答をいただきました。

> * 画面イメージからすると、文字列の長さとか制限はありますか？

文字列の長さ制限は設けようと考えております。
制限方法は「健康状態・ひとこと登録機能」で考慮予定です。

> * 例えば、状況によって何か色が変わったりとかあります？

状況ごとの色分けは現状特に考えてはいません。

> * 何も登録がない場合どんな表示になります？

登録件数が0件の場合は、健康状態表示領域には何も表示されません。現在の画面仕様ですと、「TIME LINE」バーが表示されているのみになります。

> * 一覧ということですが、個人ごとの一覧になります？それとも日ごとにメンバー全員の一覧になります？

ゆくゆくはメンバー全員の健康状態一覧となる予定です。
今後のイテレーションで「アカウント登録・ログイン機能」を実装予定ですが、その際に自分と他者の健康状態が見分けられるような画面仕様に変更します。

2021-12-16 00:19 UTC, KonJuuta commented
確認しました。以下指摘になります。
- ユースケースの記載が離れているのが気になりました。1.4にユースケース記述を書くとかして欲しいです。
- ネットワークエラーで取得できない場合とか例外ケースはないのでしょうか？
- 以下の通り画面仕様を詳しく明示してほしいです。
  - 吹き出しの表示に関する仕様（下が最新になる、スクロールするなど）
  - 名前、日時、コメント、健康状態の表示位置に関する仕様（それぞれの表示位置、日時フォーマット、タイムゾーンなど）
  - 健康状態に関する仕様（4段階とは具体的には何か、アイコンの種類など）

2021-12-17 01:25 UTC, ShirahamaTakuma commented
> 確認しました。以下指摘になります。

ご指摘いただきありがとうございます。
以下回答になります。

> * ユースケースの記載が離れているのが気になりました。1.4にユースケース記述を書くとかして欲しいです。

修正します。

> * ネットワークエラーで取得できない場合とか例外ケースはないのでしょうか？

ネットワークエラーに関しては、本アプリがWebアプリケーションである都合上、アプリの方でどうにかするということが難しいため、考慮しておりません。
データベース接続エラーに関しては、上の方のコメントで考慮しないと申し上げたのですが、現在考慮する方向性に切り替わりました。そのため、異常系にはデータベース接続エラーに関することを記述します。

> * 以下の通り画面仕様を詳しく明示してほしいです。
>   
>   * 吹き出しの表示に関する仕様（下が最新になる、スクロールするなど）
>   * 名前、日時、コメント、健康状態の表示位置に関する仕様（それぞれの表示位置、日時フォーマット、タイムゾーンなど）
>   * 健康状態に関する仕様（4段階とは具体的には何か、アイコンの種類など）

全て修正します。

2021-12-17 05:26 UTC, ShirahamaTakuma commented
「健康状態一覧表示機能」の機能仕様記述に対していただいたレビューを基に、以下の内容を修正しました。
2回目のレビューをよろしくお願いいたします。

■修正箇所
- 機能概要の文章修正
- ユースケース記述を1.4に移動
- ユースケース記述に例外フローを追加
- 画面仕様にエラー画面に関する仕様を追加
- タイムライン画面の仕様説明を大幅加筆・修正
    - 健康状態枠とその内容についての説明
    - 健康状態枠の並びや日時フォーマット、タイムゾーン、調子アイコンの種類についての説明
- メッセージ定義項目を追加

※データベース接続エラーに関しては考慮しないと申し上げていましたが、考慮する方針となりました。

2021-12-17 07:04 UTC, KonJuuta commented
画面の仕様の場合それってどこを言っているのか分かりづらいので以下のように明確に指定することが多いです。
![image](https://user-images.githubusercontent.com/80309469/146503276-df9ae188-0963-455f-84ff-d9c0edc6e608.png)
あと最新が上になるとありますが、Lineみたいな画面なので下に最新が来る方がしっくり来るかと思いました。
（対応するかはおまかせします。）

2021-12-17 10:46 UTC, iwanam approved these changes
ちなみに、プルリクのタイトルは内容を端的に表すほうがいいですね。

2021-12-20 03:04 UTC, ShirahamaTakuma commented
「健康状態一覧表示機能」の機能仕様記述に対していただいたレビューを基に、以下の内容を修正しました。
3回目のレビューをよろしくお願いいたします。

■修正箇所
- タイムライン画面の各部位を赤枠で包囲して番号割り振り。

[機能仕様書プレビュー](https://htmlpreview.github.io/?https://github.com/ShirahamaTakuma/healthcare_application/blob/health_timeline_document/doc/functional_specification/functional_specification.html)

2021-12-20 06:02 UTC, KonJuuta approved these changes

2021-12-22 02:11 UTC, merged