機能仕様書に「健康状態登録機能」の機能仕様を記述しました。
ShirahamaTakuma/healthcare_application pull request #2
Opened 2021-12-16 04:28 UTC by ShirahamaTakuma

健康状態管理アプリの2つ目の機能である「健康状態登録機能」の仕様について、機能仕様書に記述しました。
機能仕様書のレビューをよろしくお願いいたします。
また、プルリクエストの文面・記載事項に対する指摘点もございましたら、いただけると幸いです。

※本コミットには、先日レビュー依頼させていただいた「健康状態一覧表示機能」における修正内容は反映されておりません。「健康状態一覧表示機能」の方の修正が進み次第、随時こちらにも「健康状態一覧表示機能」の修正を反映していく予定です。
※「健康状態一覧表示機能」に関するレビューは変わらず、先日お送りしたプルリクエストの方からよろしくお願いいたします。

機能仕様書プレビュー

2021-12-16 07:41 UTC, iwanam requested changes
きっと考えているんだろうけどいくつか
- 状態を選択したかどうかはユーザからどう見えますか？
- ひとことに21文字目を入力するとどうなりますか？
- 「そして」は変かなぁ
- 必須の範囲がどこまでか、今のデザインだと明示的にわからないかもしれないです

コメント
- 今回はエラーチェックの練習のためこうしているんだと思うんでいいんですが、UX的には必須を入れるまでボタンを押せないほうが親切になります
- 前回今さん？が指摘してましたが、文言で書いている顔の名前(よい　とか）の対応付けをしたほうがいいですね。表情からわかるでしょうみたいなのは割と危険だったりします

2021-12-17 06:49 UTC, KonJuuta commented
健康状態登録画面の仕様について確認しました。
エラーの仕様とか無くなるので、必須の今日の調子が選択されるまでは登録ボタンを押せなくする、でも良いかと思いました。
好みの問題なので対応はお任せします。

2021-12-20 02:46 UTC, ShirahamaTakuma commented
「健康状態登録機能」の機能仕様記述に対していただいたレビューを基に、以下の内容を修正しました。
2回目のレビューをよろしくお願いいたします。
特に指摘点が無いようでしたら、approveをよろしくお願いいたします。

■仕様変更
- 健康状態登録画面の登録ボタンは、必須項目を全て選択するまで押せない仕様に変更

■修正箇所
- タイムライン画面および健康状態登録画面のレイアウト修正
    - 赤枠で各部位を分かりやすく表示
    - 健康状態登録画面からメッセージ領域を削除
    - 健康状態登録画面の調子選択欄に、表情に該当する調子を文字列で併記
    - 健康状態登録画面において、必須箇所を細かく指定
- 機能仕様および画面仕様に、ひとことが21文字以上入力出来ない旨を追記
- 機能仕様および画面仕様に、健康状態登録画面で調子選択した際の表示について追記
- ユースケース記述に、データベース接続エラーの例外フローを追記

[機能仕様書プレビュー](https://htmlpreview.github.io/?https://github.com/ShirahamaTakuma/healthcare_application/blob/health_status_registration_document/doc/functional_specification/functional_specification.html)

2021-12-20 08:22 UTC, iwanam requested changes
あえて一つ
未入力で登録するとメッセージ02が登録されるのであれば、入力欄に薄く表示するのはメッセージ02のほうが直感的なのではと思うのだけどどうだろう？

2021-12-21 02:08 UTC, KonJuuta approved these changes

2021-12-21 02:17 UTC, ShirahamaTakuma commented
> 未入力で登録するとメッセージ02が登録されるのであれば、入力欄に薄く表示するのはメッセージ02のほうが直感的なのではと思うのだけどどうだろう？

改めて考えると、そちらの方が良いと思いましたので、対応しました。
ご確認のほど、よろしくお願いいたします。

■修正箇所
- ひとこと入力欄内の薄い文字列を、未入力の際に自動で登録されるひとことメッセージに変更。
- ひとこと入力欄下にひとことメッセージの文字数制限に関する注意を記述。

[機能仕様書プレビュー](https://htmlpreview.github.io/?https://github.com/ShirahamaTakuma/healthcare_application/blob/health_status_registration_document/doc/functional_specification/functional_specification.html)

2021-12-21 04:41 UTC, ShirahamaTakuma commented
■修正箇所
- 健康状態登録画面の画面仕様における言葉遣いを微修正。
- 薄く表示されている文字列を画面仕様説明の方では修正し忘れていたため、適切な文字列に修正。

2021-12-21 07:56 UTC, iwanam approved these changes

2021-12-22 02:08 UTC, merged